[build]
builder = "nixpacks"
buildCommand = "npm install && npm run generate && npm run build"

[deploy]
startCommand = "npm run migrate:deploy && npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
